const dictionary = [
  "verboemelen",
  "verbrassen",
  "verbruiken",
  "verdelgen",
  "verdoen",
  "verdoezelen",
  "verkloten",
  "verknoeien",
  "verkwanselen",
  "verkwijnen",
  "verkwisten",
  "verlakken",
  "verleppen",
  "verloederen",
  "verlummelen",
  "verontachtzamen",
  "verontheiligen",
  "verontreinigen",
  "verprutsen",
  "verrotten",
  "verschralen",
  "verslonzen",
  "verspatten",
  "verspelen",
  "verspillen",
  "verstieren",
  "verteren",
  "vertergen",
  "verzinken",
];

export const getRandomWord = () =>
  dictionary[Math.floor(Math.random() * dictionary.length)];
